// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDrPL4932rQGJZrXSx_NdVVSK6MDvhRB-Y',
//     appId: '1:523279655368:android:521af4531976bf788ba0fd',
//     messagingSenderId: '523279655368',
//     projectId: 'tezsell-2c2f4',
//     storageBucket: 'tezsell-2c2f4.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyD8n6jFOQLyqMR0A704rDneXRaULVqhdI4',
//     appId: '1:523279655368:ios:0f4323fe1915b7038ba0fd',
//     messagingSenderId: '523279655368',
//     projectId: 'tezsell-2c2f4',
//     storageBucket: 'tezsell-2c2f4.firebasestorage.app',
//     iosBundleId: 'tezsell.com.app',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyD8n6jFOQLyqMR0A704rDneXRaULVqhdI4',
//     appId: '1:523279655368:ios:6aac181fcc00a80b8ba0fd',
//     messagingSenderId: '523279655368',
//     projectId: 'tezsell-2c2f4',
//     storageBucket: 'tezsell-2c2f4.firebasestorage.app',
//     iosBundleId: 'com.example.app',
//   );
// }
